# Generated by Django 5.2.17 on 2026-09-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterField(
            model_name="room",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "created"], name="base_messag_room_id_0e1ba5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-created"], name="base_messag_created_c02514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["-updated", "-created"], name="base_room_updated_3415ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["host"], name="base_room_host_id_4b0812_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["topic"], name="base_room_topic_i_6ee140_idx"),
        ),
        migrations.AddIndex(
            model_name="userfollowing",
            index=models.Index(
                fields=["following_user_id"], name="base_userfo_followi_17e798_idx"
            ),
        ),
    ]
